export default [
    {
        avatar: "https://i.pravatar.cc/128?img=1",
        name: "Chandler Jacobi",
        job: "Direct Security Executive",
        amount: 989.4,
        status: "primary",
        date: "Mon Feb 03 2020 04:13:15 GMT-0300 (Brasilia Standard Time)",
    },
    {
        avatar: "https://i.pravatar.cc/128?img=2",
        name: "Monserrat Marquardt",
        job: "Forward Accountability Producer",
        amount: 471.44,
        status: "danger",
        date: "Fri Nov 29 2019 10:43:17 GMT-0300 (Brasilia Standard Time)",
    },
    {
        avatar: "https://i.pravatar.cc/128?img=3",
        name: "Lonie Wyman",
        job: "Legacy Program Director",
        amount: 934.24,
        status: "success",
        date: "Fri Apr 03 2020 03:07:53 GMT-0300 (Brasilia Standard Time)",
    },
    {
        avatar: "https://i.pravatar.cc/128?img=4",
        name: "Corine Abernathy",
        job: "Chief Factors Planner",
        amount: 351.28,
        status: "warning",
        date: "Fri Jun 21 2019 20:21:55 GMT-0300 (Brasilia Standard Time)",
    },
    {
        avatar: "https://i.pravatar.cc/128?img=5",
        name: "Lorenz Botsford",
        job: "Central Accountability Developer",
        amount: 355.3,
        status: "neutral",
        date: "Wed Aug 28 2019 15:31:43 GMT-0300 (Brasilia Standard Time)",
    },
    {
        avatar: "https://i.pravatar.cc/128?img=6",
        name: "Everette Botsford",
        job: "Product Group Architect",
        amount: 525.42,
        status: "success",
        date: "Thu Jan 16 2020 09:53:33 GMT-0300 (Brasilia Standard Time)",
    },
    {
        avatar: "https://i.pravatar.cc/128?img=7",
        name: "Marilou Beahan",
        job: "Future Security Planner",
        amount: 414.99,
        status: "success",
        date: "Mon Oct 28 2019 14:44:31 GMT-0300 (Brasilia Standard Time)",
    },
    {
        avatar: "https://i.pravatar.cc/128?img=8",
        name: "Ceasar Sauer",
        job: "Direct Brand Specialist",
        amount: 488.0,
        status: "primary",
        date: "Tue Jul 23 2019 00:24:44 GMT-0300 (Brasilia Standard Time)",
    },
    {
        avatar: "https://i.pravatar.cc/128?img=9",
        name: "Rae McDermott",
        job: "Lead Branding Engineer",
        amount: 502.69,
        status: "danger",
        date: "Sat Feb 01 2020 12:57:03 GMT-0300 (Brasilia Standard Time)",
    },
    {
        avatar: "https://i.pravatar.cc/128?img=10",
        name: "Mable Steuber",
        job: "National Group Executive",
        amount: 911.09,
        status: "danger",
        date: "Mon Sep 09 2019 12:03:25 GMT-0300 (Brasilia Standard Time)",
    },
    {
        avatar: "https://i.pravatar.cc/128?img=11",
        name: "Julian Glover",
        job: "Global Branding Assistant",
        amount: 656.94,
        status: "danger",
        date: "Fri May 22 2020 17:46:12 GMT-0300 (Brasilia Standard Time)",
    },
    {
        avatar: "https://i.pravatar.cc/128?img=12",
        name: "Duncan Toy",
        job: "Central Intranet Manager",
        amount: 120.78,
        status: "danger",
        date: "Sun Nov 17 2019 11:59:50 GMT-0300 (Brasilia Standard Time)",
    },
    {
        avatar: "https://i.pravatar.cc/128?img=13",
        name: "Blanche Friesen",
        job: "Forward Identity Executive",
        amount: 676.95,
        status: "danger",
        date: "Sun Jun 21 2020 16:46:39 GMT-0300 (Brasilia Standard Time)",
    },
    {
        avatar: "https://i.pravatar.cc/128?img=14",
        name: "Orion Koepp",
        job: "Global Accountability Strategist",
        amount: 447.56,
        status: "danger",
        date: "Thu Jun 04 2020 18:29:41 GMT-0300 (Brasilia Standard Time)",
    },
    {
        avatar: "https://i.pravatar.cc/128?img=15",
        name: "Dakota Vandervort",
        job: "Future Assurance Coordinator",
        amount: 765.22,
        status: "danger",
        date: "Fri Jan 31 2020 13:02:55 GMT-0300 (Brasilia Standard Time)",
    },
];
